language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

before_script:
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME

jdk:
  - openjdk7
#  - oraclejdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  matrix:
    - PHASE='-Ptest'
    - PHASE='-Prake -Dtask=test:jruby'
    - PHASE='-Prake -Dtask=test:mri'
    - PHASE='-Prake -Dtask=test:slow_suites'
    - PHASE='-Prake -Dtask=test:tracing'
    - PHASE='-Prake -Dtask=spec:ji'
    - PHASE='-Prake -Dtask=spec:compiler'
    - PHASE='-Prake -Dtask=spec:ffi'
    - PHASE='-Prake -Dtask=spec:regression'
    - PHASE='-Prake -Dtask=spec:ruby:fast'
    - PHASE='-Prake -Dtask=spec:jruby'
    - PHASE='-Prake -Dtask=spec:jrubyc'
    - PHASE='-Prake -Dtask=spec:profiler'
    - PHASE='-Ptruffle-specs-language'
    - PHASE='-Ptruffle-specs-core'
    - PHASE='-Ptruffle-specs-rubysl'

matrix:
  include:
    # these profile do no need to run for all JDKs
    - env: PHASE='-Pdist'
      jdk: oraclejdk8
    - env: PHASE='-Pjruby-jars'
      jdk: openjdk7
    - env: PHASE='-Pmain'
      jdk: oraclejdk7
    - env: PHASE='-Pcomplete'
      jdk: oraclejdk8
    - env: PHASE='-Posgi'
      jdk: openjdk7
    - env: PHASE='-Pj2ee'
      jdk: oraclejdk7
    - env: PHASE='-Pjruby-jars,test -Dinvoker.test=extended'
      jdk: oraclejdk7
    - env: PHASE='-Pmain,test -Dinvoker.test=extended'
      jdk: openjdk7
    - env: PHASE='-Pjruby_complete_jar_extended -Dinvoker.skip=true'
      jdk: oraclejdk8
    - env: COMMAND=test/check_versions.sh
      jdk: oraclejdk8
    - env: COMMAND=tool/truffle-findbugs.sh
      jdk: oraclejdk8
  fast_finish: true
  allow_failures:
    - env: PHASE='-Pcomplete'
    - env: PHASE='-Prake -Dtask=spec:jrubyc'
    - env: PHASE='-Prake -Dtask=spec:profiler'
    - env: COMMAND=tool/truffle-findbugs.sh

script: if [[ -v COMMAND ]]; then $COMMAND; else travis_retry mvn -Pbootstrap clean install -Dinvoker.skip=false $PHASE | egrep -v 'Download|\\[exec\\] [[:digit:]]+/[[:digit:]]+|^[[:space:]]*\\[exec\\][[:space:]]*$' ; [ ${PIPESTATUS[0]} == 0 ]; fi
install: /bin/true
